STS-43 validator bonding
CasperLabs/nctl pull request #8
Opened 2020-10-09 13:28 UTC by momipsl

- Renamed commands:
`
nctl-log-view -> nctl-view-node-log
`

- New commands:
`
nctl-view-node-storage
nctl-wg-200 
nctl-wg-201 
nctl-wg-210 
nctl-wg-211 
`

- Command synonyms
`
nctl-down  ==  nctl-stop
nctl-up  ==  nctl-start

nctl-do-transfer == nctl-wg-100
nctl-do-transfer-wasm == nctl-wg-110
nctl-do-pos-submit-bid == nctl-wg-200
nctl-do-pos-withdraw-bid == nctl-wg-201
nctl-do-pos-delegate == nctl-wg-210
nctl-do-pos-undelegate == nctl-wg-211
`

- Command behaviour changes
`
nctl-compile-client - compiles all client side contracts as well as client itself
`

2020-10-09 22:33 UTC, linclelinkpart5 reviewed
Makes sense, I appreciate the aliasing, and the new name for `nctl-view-node-log`!

2020-10-10 21:15 UTC, Fraser999 requested changes
A few issues:

* For `nctl-wg-210` I get `nctl-wg-210: command not found`.
* For `nctl-do-auction-delegate` I get a panic with `can't parse  as PublicKey: AsymmetricKey("too short")`
* For `nctl-wg-211` I get a panic with `can't parse  as PublicKey: AsymmetricKey("too short")`
* For `nctl-do-auction-undelegate` I get `bash: /home/fraser/Rust/nctl/sh/generators/wg_212.sh: No such file or directory`

2020-10-12 15:42 UTC, momipsl commented on docs/commands.md
> +e.g. `nctl-wg-110 net=1 node=1 payment=200000 gas=10 transfers100 interval=0.01 user=1`  (same as above)
Fixed

2020-10-12 15:42 UTC, momipsl commented on docs/commands.md
> +Dispatches to node Y in network X from user #U, a Proof-Of-Stake auction bid **submission** for amount amount A (motes) with a delegation rate of R.  Displays relevant deploy hash for subsequent quer
Fixed

2020-10-12 15:42 UTC, momipsl commented on docs/commands.md
> +Dispatches to node Y in network X from user #U, a Proof-Of-Stake auction bid **withdrawal** for amount amount A (motes).  Displays relevant deploy hash for subsequent querying.
Fixed

2020-10-12 15:42 UTC, momipsl commented on docs/commands.md
> +Dispatches to node Y in network X from user #U, a Proof-Of-Stake **delegate** bid for amount amount A (motes).  Displays relevant deploy hash for subsequent querying.
Fixed

2020-10-12 15:42 UTC, momipsl commented on docs/commands.md
> +Dispatches to node Y in network X from user #U, a Proof-Of-Stake **undelegate** bid for amount amount A (motes).  Displays relevant deploy hash for subsequent querying.
Fixed

2020-10-12 15:42 UTC, momipsl commented on docs/installation.md
> +make make setup-rs
Fixed

2020-10-12 19:58 UTC, merged